name: Build and Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set env
        run: cp .env.example .env

      - name: Clean cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm run bootstrap

      - name: Create .env
          uses: SpicyPizza/create-envfile@v1
          with:
            MNEMONIC: ${{ secrets.MNEMONIC }}
            MUMBAI_URL: ${{ secrets.MUMBAI_URL }}
            POLYGON_MAINNET_URL: ${{ secrets.POLYGON_MAINNET_URL }}
            POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
            COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
            file_name: .env

      - name: Build
        run: npm run build:smart-contracts

      - name: Test
        run: npm run test:smart-contracts
