name: Build and Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clean cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm run bootstrap

      - name: Build
        run: npm run build:smart-contracts

      - name: Test
        run: npm run test:smart-contracts

